apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "super-demo-26"
  description: "demo-app"
  annotations:
    github.com/project-slug: leemills83/super-app-26
    backstage.io/techdocs-ref: url:https://github.com/leemills83/super-app-26
spec:
  type: website
  lifecycle: experimental
  owner: "leemills83"
